- name: Launch a custom EC2 instance
  hosts: localhost
  remote_user: ubuntu
  vars:
    volume_size: 22
    region: us-east-2

  tasks:
    - name: Launch instance
      ec2:
        image: ami-03d64741867e7bb94
        instance_profile_name: EC2FULL
        region: us-east-2
        key_name: admin_key
        vpc_subnet_id: subnet-06221544c996c7042
        instance_tags:
          Name: custom
        group: ['default', 'allow_ssh']
        instance_type: t2.micro
        user_data: |
          #!/bin/bash
          yum install -y jq awscli
          INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
          echo here
          echo ${INSTANCE_ID}
          VOLUME_ID=$(aws --region={{ region }} ec2 describe-volumes --filters Name=attachment.instance-id,Values=${INSTANCE_ID} | jq -r '.Volumes[0].VolumeId')
          echo there
          echo ${VOLUME_ID}
          aws --region={{ region }} ec2 modify-volume --volume-id ${VOLUME_ID} --size {{ volume_size }}
