- name: Launch a custom EC2 instance
  hosts: localhost
  remote_user: ec2-user
  vars_files:
  - ../config/aws.yml
  tasks:
    - name: Get latest AMI ID
      command: ../util/get-latest-ami.sh
      register: latestami

    - debug: var=latestami.stdout

    - name: Create instance
      ec2:
        image: "{{ latestami.stdout }}"
        instance_profile_name: EC2FULL
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        vpc_subnet_id: subnet-06221544c996c7042
        instance_tags:
          Name: custom
        groups: ['default', 'allow_ssh', 'web_from_alb']
        instance_type: t2.micro
        wait: yes
        user_data: |
          #!/bin/bash
          echo "hellp"
          yum update -y
          yum install -y httpd.x86_64
          systemctl start httpd.service
          systemctl enable httpd.service
          echo "Hello World from $(hostname -f)" > /var/www/html/index.html
      register: new_instance

    - name: Add new instance to Host group
      add_host:
        hostname: "{{ item.public_ip }}"
        group: new_instances
      with_items: "{{ new_instance.instances }}"

    - name: debug
      debug: var=new_instance

    - name: Create extra volume
      ec2_vol:
        device_name: /dev/xvdf
        instance: "{{ item.id }}"
        volume_size: 20
        delete_on_termination: no
        state: present
        region: "{{ region }}"
      with_items: "{{ new_instance.instances }}"
      register: new_volume

    - debug: var=new_volume

    - name: Wait for volume to be in use
      ec2_vol_info:
        filters: 
          volume-id: "{{ item.volume_id }}"
      register: vol_info
      # until: vol_info.results.volumes.status == "in-use"
      # retries: 5
      # delay: 5
      with_items: "{{ new_volume.results }}"

    - debug: var=vol_info.results

- name: Do stuff on remote
  hosts: new_instances
  remote_user: ec2-user
  become: true

  tasks:
    - name: Format extra device
      filesystem: 
        dev: /dev/xvdf
        fstype: ext4

    - name: Mount device to data
      mount:
        src: /dev/xvdf
        path: /data
        state: mounted
        fstype: ext4

    - name: Create temp file
      file:
        path: /data/myfile.txt
        state: touch
        owner: ec2-user
        group: ec2-user
        mode: 0644

    - name: Echo some stuff to file
      shell: >-
        echo "here is my first file" > /data/myfile.txt

- name: Return to localhost and take snapshot
  hosts: localhost
  become: no

  tasks:

    - debug: var=new_volume
    - name: Create volume snapshot
      ec2_snapshot:
        volume_id: "{{ item.volume_id }}"
        wait: yes
        state: present
      with_items: "{{ new_volume.results }}"

    # - name: Format instance
# 
    # - name: Mount instance to /data
# 
    # - name: Write file to /data 
# 
    # - name: Create snapshot of drive
# 
    # - name: Write file to /data
# 
    # - name: Query snapshot ID
# 
    # - name: Detach old volume from instance
# 
    # - name: Create volume from snapshot ID and attach to instance
# 
    # - name: Mount new volume to same directory

# 
    # - debug: var=instance_info
      # tags: always
# 
    # - debug: var=instance_info.instances[0].network_interfaces[0].association.public_ip
      # tags: always